---
global:
  mode: "singularity"
  file: "result_profile.json"
  rundir: "/tmp/hep-spec_wd3"
  # mp_num: "48"
  benchmarks:
    - "db12"
    - "hs06_32"
    - "hs06_64"
  tags:
    cloud: "Suite CI"
    vo: "Some VM"
    other_tag: "Some text"
  uid: "machineX"

hepspec06:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:qa"
  url_tarball: "https://example.com"
  # Define writeable directory for SPEC install in unpriveliged containers
  hepspec_volume: "/tmp/SPEC"
