---
global:
  mode: "singularity"
  file: "result_profile.json"
  rundir: "/tmp/hep-spec_wd3"
  # mp_num: "48"
  benchmarks:
    - "db12"
    - "hs06_32"
    - "hs06_64"
  tags:
    cloud: "Suite CI"
    vo: "Some VM"
    other_tag: "Some text"
  uid: "machineX"

hepspec06:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:qa"
  # URL to fetch the hepspec06. It will only be used if the software is  not found under hepspec_volume.
  url_tarball: "https://www.example.com/"
  # Define the location on where hepspec06 should be found
  # If hepspec06 is not present, the directory should be writeable to allow the installation via the url_tarball
  hepspec_volume: "/tmp/SPEC"
  # Number of iterations to run the benchmark
  iterations: 1
  # Run only a benchmark set
  bmk_set: '453.povray'

spec2017:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:qa"
  # URL to fetch the spec2017. It will only be used if the software is not found under hepspec_volume.
  url_tarball: "https://www.example.com/"
  # Define the location on where spec2017 should be found
  # If spec2017 is not present, the directory should be writeable to allow the installation via the url_tarball
  hepspec_volume: "/tmp/SPEC"
  # Number of iterations to run the benchmark
  iterations: 1
  # Run only a benchmark set
  #bmk_set: '508.namd_r'

hepscore_benchmark:
  benchmarks:
    atlas-gen-bmk:
      ref_scores:
        gen: 384
      args:
        scorekey: wl-scores
        threads: 1
        events: 200
        version: v1.2
    atlas-sim-bmk:
      ref_scores:
        sim: 0.0641
      args:
        scorekey: wl-scores
        threads: 4
        events: 10
        version: v1.1
    cms-gen-sim-bmk:
      ref_scores:
        gen-sim: 0.726
      args:
        scorekey: wl-scores
        threads: 4
        events: 20
        version: v1.2
    cms-digi-bmk:
      ref_scores:
        digi: 3.58
      args:
        scorekey: wl-scores
        threads: 4
        events: 50
        version: v1.3
    cms-reco-bmk:
      ref_scores:
        reco: 2.196
      args:
        scorekey: wl-scores
        threads: 4
        events: 50
        version: v1.2
    lhcb-gen-sim-bmk:
      ref_scores:
        gen-sim: 90.29
      args:
        scorekey: wl-scores
        threads: 1
        events: 5
        version: v0.15
  app_info:
    name: HEPscore19
    reference_machine: "CPU Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz"
    registry: gitlab-registry.cern.ch/hep-benchmarks/hep-workloads
  settings:
    method: geometric_mean
    repetitions: 3
    scaling: 355
    container_exec: docker
