---
global:
  # Type of container technology to use: Singularity or Docker
  mode: "singularity"
  # Run directory where all related suite material will be placed.
  # User should have Write permissions to the specificed directory.
  rundir: "/tmp/hep-benchmark-suite"
  # Specify the number of cores available for benchmark
  # Default will fetch all available CPUs
  # mp_num: "48"
  # Specify the list of benchmarks to run
  benchmarks:
    - "db12"
  #  - "hs06_32"
  #  - "hs06_64"
  #  - "spec2017"
  #  - "hepscore"
  # User defined tags that will show on the metadata file
  tags:
    cloud: "Suite CI"
    vo: "Some VM"
    other_tag: "Some text"
  # An extra machine identifier
  uid: "machineX"
  # enable AMQ reporting using credentials in activemq
  publish: False

# Section to configure ActiveMQ
activemq:
  server: 'your-AMQ-server.com'
  port: 61613
  topic: 'hepscore-topic'
  username: 'user'
  password: 'pw'
  key: 'key-file.key'
  cert: 'cert-file.pem'

# Section to configure HEPSpec06 benchmark
hepspec06:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:v1.0"
  # URL to fetch the hepspec06. It will only be used if the software
  # is  not found under hepspec_volume.
  url_tarball: "https://www.example.com/"
  # Define the location on where hepspec06 should be found
  # If hepspec06 is not present, the directory should be writeable
  # to allow the installation via the url_tarball
  hepspec_volume: "/tmp/SPEC"
  # Number of iterations to run the benchmark
  iterations: 3
  # Run only a benchmark set
  # bmk_set: '453.povray'

# Section to configure Spec2017 benchmark
spec2017:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:v1.0"
  # URL to fetch the spec2017. It will only be used if the software
  # is not found under hepspec_volume.
  url_tarball: "https://www.example.com/"
  # Define the location on where spec2017 should be found
  # If spec2017 is not present, the directory should be writeable
  # to allow the installation via the url_tarball
  hepspec_volume: "/tmp/SPEC"
  # Number of iterations to run the benchmark
  iterations: 3
  # Run only a benchmark set
  # bmk_set: '508.namd_r'

# Section to configure HEPScore benchmark
hepscore:
  # Select which version of hep-score to use
  version: "v1.0rc10"
  # Users can provide an alternative config file, three options are possible:
  # "default"  - Uses the default configuration provided with hepscore.
  # local path - Search locally for the configuration.
  # remote     - Download from a remote url the configuration and uses it.
  config: "default"
  # config: "tests/hepscore_ci.yaml"
  # config: "https://"
