---
global:
  mode: "singularity"
  file: "result_profile.json"
  rundir: "/tmp/hep-benchmark-suite"
  # mp_num: "48"
  benchmarks:
    - "db12"
    - "hs06_32"
    - "hs06_64"
    - "spec2017"
    - "hepscore"
  tags:
    cloud: "Suite CI"
    vo: "Some VM"
    other_tag: "Some text"
  uid: "machineX"
  # enable AMQ reporting using credentials in activemq
  publish: False

# Section to configure ActiveMQ
activemq:
  server: 'your-AMQ-server.com'
  port: 61613
  topic: 'hepscore-topic'
  username: 'user'
  password: 'pw'
  key: 'key-file.key'
  cert: 'cert-file.pem'

# Section to configure HEPSpec06 benchmark
hepspec06:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:v1.0"
  # URL to fetch the hepspec06. It will only be used if the software
  # is  not found under hepspec_volume.
  url_tarball: "https://www.example.com/"
  # Define the location on where hepspec06 should be found
  # If hepspec06 is not present, the directory should be writeable
  # to allow the installation via the url_tarball
  hepspec_volume: "/tmp/SPEC"
  # Number of iterations to run the benchmark
  iterations: 1
  # Run only a benchmark set
  # bmk_set: '453.povray'

# Section to configure Spec2017 benchmark
spec2017:
  image: "gitlab-registry.cern.ch/hep-benchmarks/hep-spec/hepspec-cc7:v1.0"
  # URL to fetch the spec2017. It will only be used if the software
  # is not found under hepspec_volume.
  url_tarball: "https://www.example.com/"
  # Define the location on where spec2017 should be found
  # If spec2017 is not present, the directory should be writeable
  # to allow the installation via the url_tarball
  hepspec_volume: "/tmp/SPEC"
  # Number of iterations to run the benchmark
  iterations: 1
  # Run only a benchmark set
  # bmk_set: '508.namd_r'

# Section to configure HepScore benchmark
# config taken from hepscore20_0_2.yaml
hepscore_benchmark:
  benchmarks:
    atlas-gen-bmk:
      ref_scores:
        gen: 384
      version: v1.2
      args:
        # threads
        -t: 1
        # events
        -e: 200
    cms-gen-sim-bmk:
      ref_scores:
        gen-sim: 0.726
      version: v1.2
      args:
        # threads
        -t: 4
        # events
        -e: 20
    cms-digi-bmk:
      ref_scores:
        digi: 3.58
      version: v1.3
      args:
        # threads
        -t: 4
        # events
        -e: 50
    cms-reco-bmk:
      ref_scores:
        reco: 2.196
      version: v1.2
      args:
        # threads
        -t: 4
        # events
        -e: 50
    lhcb-gen-sim-bmk:
      ref_scores:
        gen-sim: 90.29
      version: v0.15
      args:
        # threads
        -t: 1
        # events
        -e: 5
  app_info:
    name: HEPscore20
    reference_machine: "CPU Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz"
    registry: docker://gitlab-registry.cern.ch/hep-benchmarks/hep-workloads
  settings:
    method: geometric_mean
    repetitions: 3
    scaling: 355
    container_exec: singularity
